# Generated by Django 6.0 on 2025-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_facility_role_requirement',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='facility_name',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='location',
            new_name='location_detail',
        ),
        migrations.AddField(
            model_name='facility',
            name='city_or_state',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='facility',
            name='country',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REPORTER', 'Reporter'), ('MONITOR', 'Monitor'), ('ADMIN', 'Administrator')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', False), ('role', 'REPORTER')), models.Q(('facility__isnull', True), ('role', 'MONITOR')), models.Q(('facility__isnull', True), ('role', 'ADMIN')), _connector='OR'), name='user_facility_role_requirement'),
        ),
    ]
