# Generated by GitHub Copilot on 2026-01-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_user_facility_role_requirement_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_facility_role_requirement",
        ),
        migrations.RenameField(
            model_name="facility",
            old_name="facility_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="facility",
            old_name="city_or_state",
            new_name="city",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="location_detail",
        ),
        migrations.AlterField(
            model_name="facility",
            name="country",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="facility",
            unique_together={("name", "country", "city")},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(role="REPORTER", facility__isnull=False)
                    | models.Q(role="MONITOR", facility__isnull=True)
                    | models.Q(role="ADMIN", facility__isnull=True)
                ),
                name="user_facility_role_requirement",
            ),
        ),
    ]
