# Generated by Django 6.0 on 2026-01-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_facility_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='ResourceReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icu_beds_available', models.PositiveIntegerField()),
                ('ventilators_available', models.PositiveIntegerField()),
                ('staff_on_duty', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='core.facility')),
            ],
            options={
                'verbose_name_plural': 'Resource report histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
