# Generated by Django 6.0 on 2026-01-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_facility_city_resourcereporthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting identifier', max_length=100, unique=True)),
                ('value', models.CharField(help_text='Setting value', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('setting_type', models.CharField(choices=[('THRESHOLD', 'Threshold'), ('GENERAL', 'General'), ('ALERT', 'Alert')], default='GENERAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System settings',
                'ordering': ['setting_type', 'key'],
            },
        ),
    ]
