from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health_check, name="health_check"),
    path("reporter/report/", views.ReporterResourceReportView.as_view(),
         name="reporter_resource_report"),
    path("monitor/dashboard/", views.MonitorDashboardView.as_view(),
         name="monitor_dashboard"),
    path("monitor/dashboard/export/", views.MonitorExportDashboardView.as_view(),
         name="monitor_export_dashboard"),
    path("monitor/trend/", views.MonitorTrendView.as_view(),
         name="monitor_trend"),
    path("admin/create-user/", views.AdminCreateUserView.as_view(),
         name="admin_create_user"),
    path("admin/users/list/", views.AdminUserListView.as_view(),
         name="admin_list_users"),
    path("admin/users/<int:user_id>/", views.AdminUserDetailView.as_view(),
         name="admin_user_detail"),
    path("admin/users/export/", views.AdminExportUsersView.as_view(),
         name="admin_export_users"),
    path("admin/facilities/", views.AdminFacilityView.as_view(),
         name="admin_facilities"),
    path("admin/stats/", views.AdminPlatformStatsView.as_view(),
         name="admin_platform_stats"),
    path("admin/settings/", views.AdminSettingsListView.as_view(),
         name="admin_settings_list"),
    path("admin/settings/<int:setting_id>/", views.AdminSettingsDetailView.as_view(),
         name="admin_settings_detail"),
    path("admin/settings/initialize/", views.AdminSettingsInitializeView.as_view(),
         name="admin_settings_initialize"),
    path("settings/public/", views.PublicSettingsView.as_view(),
         name="public_settings"),
]
